apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: example-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
      - name: example-service
        image: TARGET_DOCKER_REGISTRY/example-service:VERSION
        args: ["run"]
